server:
  service:
    servicePortHttpAppProtocol: kubernetes.io/h2c
    servicePortHttpsAppProtocol: kubernetes.io/h2c

configs:
  params:
    server.insecure: true
  cm:
    url: "https://argocd.itruslan.ru"
    oidc.config: |
      name: Authentik
      issuer: https://auth.itruslan.ru/application/o/argocd/
      clientID: argocd
      clientSecret: $oidc.clientSecret
      requestedScopes:
        - openid
        - profile
        - email
      logoutURL: https://auth.itruslan.ru/application/o/argocd/end-session/
  rbac:
    policy.default: role:admin

redis-ha:
  enabled: false

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1
